/**
 * Stage 3 — tailor the résumé to one job, Overleaf-style.
 *
 * Left: the LaTeX, editable. Right: the compiled PDF. Nothing is generated by
 * opening this — the modal opens on an empty state with a Generate button,
 * because generating costs an LLM call (~8.8k tokens) against a daily cap.
 *
 * Why a textarea and not a code editor
 * ------------------------------------
 * CodeMirror plus a LaTeX mode is ~250KB to make `\textbf` blue in a document
 * the user mostly does not hand-edit — the tailoring writes it, and edits are
 * usually a word. A monospace textarea with line numbers keeps the dependency
 * list where it is. The line numbers exist because compile errors are reported
 * as "resume.tex:24", and a number with nothing to count against is useless.
 *
 * Why compiling is a button, not a keystroke
 * ------------------------------------------
 * A warm compile is ~3.5s (measured — see `app/latex.py`). Recompiling as you
 * type would mean a preview that is permanently one edit behind and a queue of
 * doomed builds. Ctrl/Cmd-S saves and compiles, which is the Overleaf muscle
 * memory anyway.
 *
 * The left pane has two tabs: the LaTeX editor, and a chat (`ResumeChat.tsx`)
 * for asking for changes in words. Chat sits in the left pane, not over the
 * PDF, because the preview is what the user checks each suggestion against.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  AlertTriangle,
  Check,
  Download,
  Code2,
  FileText,
  Loader2,
  MessageSquare,
  RefreshCw,
  Sparkles,
  Undo2,
  X,
} from "lucide-react";

import {
  ApiError,
  compileDocument,
  documentPdfUrl,
  documentTexUrl,
  fetchBaseResume,
  fetchDocument,
  generateDocument,
  revertDocument,
  saveDocument,
} from "../lib/api";
import type { CompileResult, FactIssue, TailoredDocument } from "../lib/types";
import { cx } from "./primitives";
import { ResumeChat } from "./ResumeChat";

type Pane = "editor" | "chat";

export function TailorModal({
  jobId,
  jobTitle,
  company,
  onClose,
}: {
  jobId: number | null;
  jobTitle: string;
  company: string;
  onClose: () => void;
}) {
  const open = jobId != null;
  const queryClient = useQueryClient();

  // The editor's working copy. `null` means "show the server's text" — kept
  // distinct from "" so an empty edit is still an edit.
  const [draft, setDraft] = useState<string | null>(null);
  const [compileState, setCompileState] = useState<CompileResult | null>(null);
  const [pdfVersion, setPdfVersion] = useState("");
  const [showLog, setShowLog] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [pane, setPane] = useState<Pane>("editor");

  const document_ = useQuery({
    queryKey: ["document", jobId],
    queryFn: () => fetchDocument(jobId!),
    enabled: open,
    staleTime: 60_000,
  });

  const base = useQuery({
    queryKey: ["base-resume"],
    queryFn: fetchBaseResume,
    enabled: open,
    staleTime: Infinity,
  });

  const doc = document_.data ?? null;
  const tex = draft ?? doc?.tex ?? "";
  const dirty = draft != null && draft !== doc?.tex;

  // Reset per job: a stale draft leaking across rows would silently overwrite
  // one résumé with another's text on the next save.
  useEffect(() => {
    setDraft(null);
    setCompileState(null);
    setPdfVersion("");
    setShowLog(false);
    setError(null);
  }, [jobId]);

  const runCompile = useCallback(
    async (docId: number) => {
      const result = await compileDocument(docId);
      setCompileState(result);
      if (result.ok) setPdfVersion(result.pdf_hash);
      return result;
    },
    [],
  );

  // First successful load compiles once, so the preview is not an empty box
  // waiting for a click the user has no reason to make.
  useEffect(() => {
    if (doc && !compileState) void runCompile(doc.id).catch(() => undefined);
  }, [doc, compileState, runCompile]);

  const generate = useMutation({
    mutationFn: (force: boolean) => generateDocument(jobId!, force),
    onSuccess: (next) => {
      queryClient.setQueryData(["document", jobId], next);
      // Regenerating starts a new conversation server-side.
      void queryClient.invalidateQueries({ queryKey: ["resume-chat", next.id] });
      setDraft(null);
      setCompileState(null);
      setError(null);
    },
    onError: (e: unknown) => setError(describe(e)),
  });

  const save = useMutation({
    mutationFn: async (text: string) => {
      const saved = await saveDocument(doc!.id, text);
      await runCompile(saved.id);
      return saved;
    },
    onSuccess: (next) => {
      queryClient.setQueryData(["document", jobId], next);
      setDraft(null);
      setError(null);
    },
    onError: (e: unknown) => setError(describe(e)),
  });

  const revert = useMutation({
    mutationFn: () => revertDocument(doc!.id),
    onSuccess: (next) => {
      queryClient.setQueryData(["document", jobId], next);
      setDraft(null);
      setCompileState(null);
    },
    onError: (e: unknown) => setError(describe(e)),
  });

  const recompile = useMutation({
    mutationFn: async () => {
      if (dirty && doc) {
        const saved = await saveDocument(doc.id, tex);
        queryClient.setQueryData(["document", jobId], saved);
        setDraft(null);
        return runCompile(saved.id);
      }
      return runCompile(doc!.id);
    },
    onError: (e: unknown) => setError(describe(e)),
  });

  useEffect(() => {
    if (!open) return;
    const onKey = (event: KeyboardEvent) => {
      if (event.key === "Escape" && !generate.isPending) onClose();
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "s") {
        event.preventDefault();
        if (doc) recompile.mutate();
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open, onClose, doc, recompile, generate.isPending]);

  if (!open) return null;

  const blocking = (doc?.issues ?? []).filter((i) => i.severity === "blocking");
  const warnings = (doc?.issues ?? []).filter((i) => i.severity === "warning");

  return (
    <>
      <div
        onClick={onClose}
        className="animate-fade-in fixed inset-0 z-40 bg-black/60 backdrop-blur-[4px]"
        aria-hidden
      />
      <div className="pointer-events-none fixed inset-0 z-50 flex items-center justify-center p-3 md:p-5">
        <div
          role="dialog"
          aria-modal="true"
          aria-label={`Tailor résumé for ${jobTitle}`}
          className="glass-strong animate-fade-up pointer-events-auto flex h-full max-h-[94vh] w-full max-w-[1500px] flex-col overflow-hidden rounded-2xl border border-edge-strong"
        >
          <Header
            jobTitle={jobTitle}
            company={company}
            doc={doc}
            dirty={dirty}
            busy={generate.isPending || save.isPending || recompile.isPending}
            compiling={recompile.isPending}
            pdfVersion={pdfVersion}
            onClose={onClose}
            onGenerate={() => generate.mutate(Boolean(doc))}
            onRecompile={() => recompile.mutate()}
            onRevert={() => revert.mutate()}
          />

          {error && (
            <div className="flex items-start gap-2 border-b border-edge bg-rose-500/10 px-4 py-2 text-[12px] text-rose-200">
              <AlertTriangle size={14} className="mt-0.5 shrink-0" />
              <span>{error}</span>
            </div>
          )}

          {!base.data?.available && base.isFetched && (
            <div className="border-b border-edge bg-amber-500/10 px-4 py-2 text-[12px] text-amber-200">
              {base.data?.note ?? "The résumé template is missing."}
            </div>
          )}

          {document_.isLoading ? (
            <Centered>
              <Loader2 className="animate-spin" size={18} />
              <span>Loading…</span>
            </Centered>
          ) : !doc ? (
            <EmptyTailorState
              busy={generate.isPending}
              onGenerate={() => generate.mutate(false)}
            />
          ) : (
            <div className="flex min-h-0 flex-1 flex-col lg:flex-row">
              <section className="flex min-h-0 flex-1 flex-col border-edge lg:max-w-[46%] lg:border-r">
                <PaneTabs pane={pane} dirty={dirty} onChange={setPane} />
                {pane === "editor" ? (
                  <>
                    <TailoringSummary doc={doc} blocking={blocking} warnings={warnings} />
                    <Editor value={tex} onChange={(next) => setDraft(next)} />
                  </>
                ) : (
                  <ResumeChat
                    doc={doc}
                    dirty={dirty}
                    onApplied={(next) => {
                      queryClient.setQueryData(["document", jobId], next);
                      setDraft(null);
                      void runCompile(next.id).catch((e: unknown) => setError(describe(e)));
                    }}
                  />
                )}
                <CompileBar
                  state={compileState}
                  dirty={dirty}
                  showLog={showLog}
                  onToggleLog={() => setShowLog((v) => !v)}
                />
              </section>

              <section className="flex min-h-0 flex-1 flex-col bg-black/20">
                <Preview
                  docId={doc.id}
                  version={pdfVersion}
                  compiling={recompile.isPending}
                  failed={compileState != null && !compileState.ok}
                  errors={compileState?.errors ?? []}
                />
              </section>
            </div>
          )}

          {showLog && compileState && (
            <pre className="max-h-40 shrink-0 overflow-auto border-t border-edge bg-black/40 px-4 py-2 font-mono text-[10.5px] leading-relaxed text-subtle">
              {compileState.log || "(no output)"}
            </pre>
          )}
        </div>
      </div>
    </>
  );
}

function PaneTabs({
  pane,
  dirty,
  onChange,
}: {
  pane: Pane;
  dirty: boolean;
  onChange: (next: Pane) => void;
}) {
  const tabs: { id: Pane; label: string; icon: React.ReactNode }[] = [
    { id: "editor", label: "LaTeX", icon: <Code2 size={12} /> },
    { id: "chat", label: "Chat", icon: <MessageSquare size={12} /> },
  ];
  return (
    <div role="tablist" className="flex shrink-0 gap-1 border-b border-edge px-3 pt-2">
      {tabs.map((tab) => (
        <button
          key={tab.id}
          role="tab"
          aria-selected={pane === tab.id}
          onClick={() => onChange(tab.id)}
          className={cx(
            "-mb-px flex items-center gap-1.5 rounded-t-lg border border-b-0 px-3 py-1.5 text-[12px] font-medium",
            pane === tab.id
              ? "border-edge bg-white/5 text-ink"
              : "border-transparent text-subtle hover:text-ink",
          )}
        >
          {tab.icon}
          {tab.label}
          {tab.id === "editor" && dirty && (
            <span className="h-1.5 w-1.5 rounded-full bg-amber-300" aria-label="unsaved edits" />
          )}
        </button>
      ))}
    </div>
  );
}

function Header({
  jobTitle,
  company,
  doc,
  dirty,
  busy,
  compiling,
  pdfVersion,
  onClose,
  onGenerate,
  onRecompile,
  onRevert,
}: {
  jobTitle: string;
  company: string;
  doc: TailoredDocument | null;
  dirty: boolean;
  busy: boolean;
  compiling: boolean;
  pdfVersion: string;
  onClose: () => void;
  onGenerate: () => void;
  onRecompile: () => void;
  onRevert: () => void;
}) {
  return (
    <header className="flex shrink-0 items-center gap-3 border-b border-edge px-4 py-3">
      <FileText size={16} className="shrink-0 text-accent" />
      <div className="min-w-0 flex-1">
        <h2 className="truncate text-[13.5px] font-semibold text-ink">
          Tailored résumé — {jobTitle}
        </h2>
        <p className="truncate text-[11.5px] text-subtle">
          {company}
          {doc && (
            <>
              {" · "}
              <span className="text-muted">draft</span>
              {doc.hand_edited && " · edited by you"}
              {doc.stale && " · the job description changed since this was written"}
              {doc.llm_tokens > 0 && ` · ${doc.llm_tokens.toLocaleString()} tokens`}
            </>
          )}
        </p>
      </div>

      <div className="flex shrink-0 items-center gap-1.5">
        {doc && (
          <>
            <ToolButton onClick={onRecompile} busy={compiling} title="Save and recompile (Ctrl+S)">
              <RefreshCw size={13} className={compiling ? "animate-spin" : undefined} />
              {dirty ? "Save & compile" : "Recompile"}
            </ToolButton>
            {doc.hand_edited && (
              <ToolButton onClick={onRevert} title="Discard your edits; free, no LLM call">
                <Undo2 size={13} />
                Revert
              </ToolButton>
            )}
            <a
              href={documentPdfUrl(doc.id, pdfVersion, true)}
              className={cx(
                "flex items-center gap-1.5 rounded-lg border border-edge px-2.5 py-1.5 text-[12px] font-medium",
                pdfVersion
                  ? "bg-accent/15 text-accent hover:bg-accent/25"
                  : "pointer-events-none opacity-40",
              )}
              title="Download the PDF you are looking at"
            >
              <Download size={13} />
              PDF
            </a>
            <a
              href={documentTexUrl(doc.id)}
              className="rounded-lg border border-edge px-2.5 py-1.5 text-[12px] text-muted hover:text-ink"
              title="Download the LaTeX source"
            >
              .tex
            </a>
          </>
        )}
        <ToolButton onClick={onGenerate} busy={busy} title="Runs one LLM call">
          <Sparkles size={13} />
          {doc ? "Regenerate" : "Generate"}
        </ToolButton>
        <button
          onClick={onClose}
          className="ml-1 rounded-lg p-1.5 text-subtle hover:bg-white/5 hover:text-ink"
          aria-label="Close"
        >
          <X size={16} />
        </button>
      </div>
    </header>
  );
}

function ToolButton({
  children,
  onClick,
  busy,
  title,
}: {
  children: React.ReactNode;
  onClick: () => void;
  busy?: boolean;
  title?: string;
}) {
  return (
    <button
      onClick={onClick}
      disabled={busy}
      title={title}
      className="flex items-center gap-1.5 rounded-lg border border-edge px-2.5 py-1.5 text-[12px] font-medium text-muted hover:text-ink disabled:opacity-50"
    >
      {busy ? <Loader2 size={13} className="animate-spin" /> : children}
    </button>
  );
}

function EmptyTailorState({ busy, onGenerate }: { busy: boolean; onGenerate: () => void }) {
  return (
    <Centered>
      <Sparkles size={22} className="text-accent" />
      <p className="max-w-sm text-center text-[13px] text-muted">
        Rewrite your résumé to lead with what this posting asks for. Your bullets are
        re-ordered and re-worded — never invented.
      </p>
      <button
        onClick={onGenerate}
        disabled={busy}
        className="flex items-center gap-2 rounded-xl bg-accent px-4 py-2 text-[13px] font-semibold text-black disabled:opacity-60"
      >
        {busy ? <Loader2 size={14} className="animate-spin" /> : <Sparkles size={14} />}
        {busy ? "Tailoring…" : "Tailor résumé"}
      </button>
      <p className="text-[11px] text-subtle">One LLM call, ~9k tokens.</p>
    </Centered>
  );
}

/** What the tailoring did, and what it was stopped from doing. */
function TailoringSummary({
  doc,
  blocking,
  warnings,
}: {
  doc: TailoredDocument;
  blocking: FactIssue[];
  warnings: FactIssue[];
}) {
  const [open, setOpen] = useState(true);
  // `reworded` mixes bullets and skills rows, so counting it as "N bullets"
  // contradicted a tailoring whose own note said no bullet was rewritten.
  const bullets = doc.reworded.filter((id) => !id.startsWith("skills."));
  const rows = doc.reworded.length - bullets.length;

  return (
    <div className="shrink-0 border-b border-edge">
      <button
        onClick={() => setOpen((v) => !v)}
        className="flex w-full items-center gap-2 px-4 py-2 text-left text-[11px] font-semibold tracking-wide text-subtle uppercase hover:text-ink"
      >
        What changed
        <span className="font-normal normal-case text-muted">
          {[
            bullets.length > 0 && `${bullets.length} bullet${bullets.length === 1 ? "" : "s"}`,
            rows > 0 && `${rows} skills row${rows === 1 ? "" : "s"}`,
            doc.dropped.length > 0 && `${doc.dropped.length} dropped`,
          ]
            .filter(Boolean)
            .join(", ") || "reordered only"}
        </span>
        <span className="ml-auto text-[10px]">{open ? "hide" : "show"}</span>
      </button>

      {open && (
        <div className="max-h-52 overflow-auto px-4 pb-3 text-[12px] leading-relaxed">
          {doc.jd_keywords.length > 0 && (
            <div className="mb-2 flex flex-wrap gap-1">
              {doc.jd_keywords.map((word) => (
                <span
                  key={word}
                  className="rounded-md border border-edge bg-panel px-1.5 py-0.5 text-[10.5px] text-muted"
                >
                  {word}
                </span>
              ))}
            </div>
          )}

          <ul className="space-y-1 text-muted">
            {doc.tailoring_notes.map((note, index) => (
              <li key={index} className="flex gap-1.5">
                <span className="text-subtle">·</span>
                <span>{note}</span>
              </li>
            ))}
          </ul>

          {blocking.length > 0 && (
            <div className="mt-2 rounded-lg border border-rose-500/30 bg-rose-500/10 p-2">
              <p className="mb-1 flex items-center gap-1.5 text-[11px] font-semibold text-rose-200">
                <AlertTriangle size={12} />
                {blocking.length} rewrite{blocking.length === 1 ? "" : "s"} rejected — your
                original wording was kept
              </p>
              <ul className="space-y-0.5 text-[11px] text-rose-200/80">
                {blocking.map((issue, index) => (
                  <li key={index}>{issue.message}</li>
                ))}
              </ul>
            </div>
          )}

          {warnings.length > 0 && (
            <div className="mt-2 rounded-lg border border-amber-500/25 bg-amber-500/5 p-2">
              <p className="mb-1 text-[11px] font-semibold text-amber-200">
                Worth a look — {warnings.length} term
                {warnings.length === 1 ? "" : "s"} not in your profile
              </p>
              <ul className="space-y-0.5 text-[11px] text-amber-200/75">
                {warnings.slice(0, 6).map((issue, index) => (
                  <li key={index}>{issue.message}</li>
                ))}
              </ul>
            </div>
          )}

          {blocking.length === 0 && warnings.length === 0 && (
            <p className="mt-2 flex items-center gap-1.5 text-[11px] text-emerald-300/80">
              <Check size={12} />
              Every claim checks out against your profile.
            </p>
          )}
        </div>
      )}
    </div>
  );
}

/** Monospace LaTeX with a gutter, so a "resume.tex:24" error can be found. */
function Editor({ value, onChange }: { value: string; onChange: (next: string) => void }) {
  const textarea = useRef<HTMLTextAreaElement>(null);
  const gutter = useRef<HTMLDivElement>(null);
  const lines = useMemo(() => value.split("\n").length, [value]);

  return (
    <div className="relative flex min-h-0 flex-1 overflow-hidden font-mono text-[12px] leading-[1.55]">
      <div
        ref={gutter}
        aria-hidden
        className="shrink-0 overflow-hidden border-r border-edge bg-black/20 py-3 pr-2 pl-3 text-right text-subtle select-none"
      >
        {Array.from({ length: lines }, (_, index) => (
          <div key={index}>{index + 1}</div>
        ))}
      </div>
      <textarea
        ref={textarea}
        value={value}
        spellCheck={false}
        onChange={(event) => onChange(event.target.value)}
        onScroll={() => {
          // The gutter is a separate element, so it has to be told to follow.
          if (gutter.current && textarea.current)
            gutter.current.scrollTop = textarea.current.scrollTop;
        }}
        className="min-h-0 flex-1 resize-none bg-transparent px-3 py-3 text-ink outline-none"
      />
    </div>
  );
}

function CompileBar({
  state,
  dirty,
  showLog,
  onToggleLog,
}: {
  state: CompileResult | null;
  dirty: boolean;
  showLog: boolean;
  onToggleLog: () => void;
}) {
  return (
    <div className="flex shrink-0 items-center gap-2 border-t border-edge px-4 py-2 text-[11.5px]">
      {state == null ? (
        <span className="text-subtle">Not compiled yet</span>
      ) : state.ok ? (
        <span className="flex items-center gap-1.5 text-emerald-300/90">
          <Check size={12} />
          Compiled in {state.duration_s}s
        </span>
      ) : (
        <span className="flex items-center gap-1.5 text-rose-300">
          <AlertTriangle size={12} />
          {state.errors[0] ?? "Compile failed"}
        </span>
      )}

      {dirty && <span className="text-amber-300/90">· unsaved edits</span>}

      {state?.fact_warnings.map((warning, index) => (
        <span key={index} className="text-amber-300/80">
          · {warning}
        </span>
      ))}

      <button onClick={onToggleLog} className="ml-auto text-subtle hover:text-ink">
        {showLog ? "hide log" : "log"}
      </button>
    </div>
  );
}

function Preview({
  docId,
  version,
  compiling,
  failed,
  errors,
}: {
  docId: number;
  version: string;
  compiling: boolean;
  failed: boolean;
  errors: string[];
}) {
  if (!version && failed) {
    return (
      <Centered>
        <AlertTriangle size={20} className="text-rose-300" />
        <p className="text-[13px] text-muted">This résumé doesn&apos;t compile.</p>
        <ul className="max-w-md space-y-1 font-mono text-[11px] text-rose-200/80">
          {errors.slice(0, 6).map((line, index) => (
            <li key={index}>{line}</li>
          ))}
        </ul>
      </Centered>
    );
  }

  if (!version) {
    return (
      <Centered>
        <Loader2 className="animate-spin" size={18} />
        <span className="text-[12px]">Compiling…</span>
      </Centered>
    );
  }

  return (
    <div className="relative min-h-0 flex-1">
      {compiling && (
        <div className="absolute top-2 right-2 z-10 flex items-center gap-1.5 rounded-lg bg-black/70 px-2 py-1 text-[11px] text-muted">
          <Loader2 size={11} className="animate-spin" />
          rebuilding
        </div>
      )}
      <iframe
        // Keyed on the version so a rebuilt PDF actually replaces the old one;
        // browsers happily keep showing a cached PDF at an unchanged URL.
        key={version}
        src={`${documentPdfUrl(docId, version)}#toolbar=1&navpanes=0&view=FitH`}
        title="Résumé preview"
        className="h-full w-full border-0 bg-neutral-800"
      />
    </div>
  );
}

function Centered({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex min-h-0 flex-1 flex-col items-center justify-center gap-3 p-8 text-muted">
      {children}
    </div>
  );
}

function describe(error: unknown): string {
  if (error instanceof ApiError) return error.message;
  return error instanceof Error ? error.message : String(error);
}
